# Generated by Django 4.0.3 on 2022-05-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0002_general_exercise_general_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='ex_hand',
            field=models.CharField(choices=[('left', 'left'), ('right', 'right')], default='right', max_length=30),
        ),
    ]
